using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Web;
using System.IO;
using System.Net.Mail;

namespace SecretSanta
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public List<String> names = new List<String>();
        public List<String> emails = new List<String>();

        public List<Contact> allContacts = new List<Contact>();

        public String emailMessageName = "";
        public String emailMessageSecretSanta = "";

        public int numberOfPeople = 0;
        public System.Windows.Media.Brush labelForeground = new SolidColorBrush(Colors.White);
        public System.Windows.Thickness marginThickness = new Thickness(10);
        public MailMessage email = new MailMessage();
        //public System.Net.Mail.MailAddress mail = new MailAddress();
        public SmtpClient smtp = new SmtpClient();

        public MainWindow()
        {
            InitializeComponent();

            UINumberPeople.TextChanged += UINumberPeople_TextChanged;

            var stackPanel = AllContacts;

            email.From = new MailAddress("SquadSecretSanta1@gmail.com");
            email.Subject = "Secret Santa";
            smtp.EnableSsl = true;
            smtp.Port = 587;
            smtp.Host = "smtp.gmail.com";
            smtp.Credentials = new System.Net.NetworkCredential("SquadSecretSanta1@gmail.com", "viking23");

            UIGenerate.Click += (o, e) =>
            {
                GenerateSecretSantas();
                foreach (var contact in allContacts)
                {

                    email.To.Clear();
                    email.To.Add(contact.emailTextbox.Text);

                    email.Body = String.Format("Ho Ho Ho, \nMerry Christmas {0}. Hope all is well for you. Your Secret Santa name is {1}. This email is autogenerated, fancy, huh?", contact.nameTextbox.Text, contact.secretSanta);

                    smtp.Send(email);
                }
            };
        }

        private void UINumberPeople_TextChanged(object sender, TextChangedEventArgs e)
        {
            AllContacts.Children.Clear();
            allContacts.Clear();
            bool test = Int32.TryParse(UINumberPeople.Text, out numberOfPeople);

            if(test){
                for (int i = 1; i <= numberOfPeople; i++)
                {
                    var tempStackPanel = new StackPanel();
                    tempStackPanel.Orientation = Orientation.Horizontal;
                    tempStackPanel.HorizontalAlignment = System.Windows.HorizontalAlignment.Center;

                    tempStackPanel.Children.Add(new Label() { Content = "Name:", FontWeight = FontWeights.Bold, Foreground = labelForeground, Margin = marginThickness });
                    TextBox Name = new TextBox() { Name = "Name" + i, FontWeight = FontWeights.Bold, Width = 100, Margin = marginThickness };
                    tempStackPanel.Children.Add(Name);

                    tempStackPanel.Children.Add(new Label() { Content = "Email:", FontWeight = FontWeights.Bold, Foreground = labelForeground, Margin = marginThickness });
                    TextBox Email = new TextBox() { Name = "Email" + i, FontWeight = FontWeights.Bold, Width = 200, Margin = marginThickness };
                    tempStackPanel.Children.Add(Email);

                    allContacts.Add(new Contact() { nameTextbox = Name, emailTextbox = Email, index = i});

                    AllContacts.Children.Add(tempStackPanel);
                }
            }
            //throw new NotImplementedException();
        }

        public void GenerateSecretSantas()
        {
            List<Contact> tempContacts = new List<Contact>();
            tempContacts.AddRange(allContacts);
            int successfulCount = 0;

            List<int> takenIntegers = new List<int>();

            while (successfulCount < 6)
            {
                tempContacts = new List<Contact>();
                tempContacts.AddRange(allContacts);

                foreach (var contact in allContacts)
                {
                    Random rand = new Random();
                    int ind = rand.Next(1, tempContacts.Count());

                    //make sure there is more than one name left in hat
                    if (tempContacts.Count() > 1)
                    {
                        //ensure random number is not own name
                        while (tempContacts.ElementAt(ind) == contact)
                        {
                            ind = rand.Next(1, tempContacts.Count());
                        }
                        successfulCount += 1;
                        contact.secretSanta = tempContacts.ElementAt(ind).nameTextbox.Text;

                        tempContacts.RemoveAt(ind);

                    }
                    else 
                    {
                        if(ind != contact.index){
                            successfulCount += 1;
                            contact.secretSanta = tempContacts.Where(p => p.index == ind).FirstOrDefault().nameTextbox.Text;
                        }
                    }

                }
            }

            foreach (var contact in allContacts)
            {
                if (contact.nameTextbox.Text == contact.secretSanta)
                {
                    bool x = true;
                }
            }
            
        }
    }

    public class Contact
    {
        public TextBox nameTextbox { get; set; }
        public TextBox emailTextbox { get; set; }

        public String name { get; set; }
        public String secretSanta { get; set; }

        public int index { get; set; }
    }
}
